config/routes.rb
Rails.application.routes.draw do
  root "pages#index"

  resources :demo1s do
    member do
      get :file_preview  # Add a route for file preview
      get :delete_file # Add a route for deleting a file
    end
  end

  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create]
  resources :folders, only: [:new, :create, :show]

  # Additional routes
  get 'users/index'
  get 'users/new'
  get 'users/create'
  get 'users/show'
  get 'folders/new'
  get 'folders/show'
  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'countries', to: 'demo1s#countries'  
  get 'cities', to: 'demo1s#cities'
  get 'states', to: 'demo1s#states'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
# app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "User created successfully,Now you can proceed to login"
      redirect_to root_path
    else
      flash[:alert] = "Username already exists try another"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>

<%= link_to 'New User', new_user_path %>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>name</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">

              <h2 class="fw-bold mb-2 text-uppercase">Signup</h2>
              <p class="text-white-50 mb-5">Please enter your Username and password!</p>
                    
              <div data-mdb-input-init class="form-outline form-white mb-4">
                
                   <%= form_with model: @user do |f| %>
                        <% if @user.errors.any? %>
                          <div>
                            <ul>
                              <% @user.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                              <% end %>
                            </ul>
                          </div>
                        <% end %>
                        <div data-mdb-input-init class="form-outline form-white mb-4">
                          <%= f.label :name %><br>
                          <%= f.text_field :name %>
                        </div>
                        <div data-mdb-input-init class="form-outline form-white mb-4">
                          <%= f.label :password %><br>
                          <%= f.password_field :password %>
                        </div>
                        <div data-mdb-input-init class="form-outline form-white mb-4">
                          <%= f.label :password_confirmation %><br>
                          <%= f.password_field :password_confirmation %>
                        </div>
                        <p>
                         <button data-mdb-button-init data-mdb-ripple-init class="btn btn-outline-light btn-lg px-5" type="submit"> Signup  </button>
                        </p>
              
            </div>
                          <div>
                          <p class="mb-0">Already have an account! <a href="#!" class="text-white-50 fw-bold"><%= link_to 'Login','/user_sessions/new'%></a>
                          </p>
                          </div>
            </div>
              
              <% end %>
             
          </div>
          
        </div>
      </div>
    </div>
  </div>
</section>