config/routes.rb
Rails.application.routes.draw do
  root "pages#index"

  resources :demo1s do
    member do
      get :file_preview  # Add a route for file preview
      get :delete_file # Add a route for deleting a file
    end
  end

  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create]
  resources :folders, only: [:new, :create, :show]

  # Additional routes
  get 'users/index'
  get 'users/new'
  get 'users/create'
  get 'users/show'
  get 'folders/new'
  get 'folders/show'
  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'countries', to: 'demo1s#countries'  
  get 'cities', to: 'demo1s#cities'
  get 'states', to: 'demo1s#states'
end

app/controllers/user_sessions_controller.rb
# app/controllers/application_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
  
  def create
    @user = User.find_by(name: params[:user][:name])

    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to demo1s_path
    else
      flash[:alert] = "Login failed"
      redirect_to new_user_session_path
    end
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/new.html.erb
<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">

              <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
              <p class="text-white-50 mb-5">Please enter your login and password!</p>
                    <%= form_with model: @user, url: user_sessions_path do |f| %>
              <div data-mdb-input-init class="form-outline form-white mb-4">
                
                    <%= f.label :name %><br>
                    <%= f.text_field :name %>

              </div>

              <div data-mdb-input-init class="form-outline form-white mb-4">
                 
                  <%= f.label :password %><br>
                  <%= f.password_field :password %>
  
              </div>



              <button data-mdb-button-init data-mdb-ripple-init class="btn btn-outline-light btn-lg px-5" type="submit"> Login</button>

            

            </div>
              <% end %>

            <div>
              <p class="mb-0">Don't have an account? <a href="#!" class="text-white-50 fw-bold"><%= link_to 'Signup','/users/new'%></a>
              </p>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>